spring.application.name=totnghiep
spring.datasource.url=jdbc:mysql://localhost:3306/totnghiep
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration - Đảm bảo tên property khớp
bezkoder.app.jwtSecret=c2VjcmV0S2V5Rm9ySldUU2lnbmluZ0FuZFZlcmlmaWNhdGlvbk9mSldUVG9rZW5zMjAyNGV4YW1wbGUzMDRiYWNrZW5kYXBw
bezkoder.app.jwtExpirationMs=86400000
bezkoder.app.jwtRefreshExpirationMs=604800000 

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


cloudinary.cloud-name=de2b5kpqu
cloudinary.api-key=397325177514936
cloudinary.api-secret=0aPr5DIQuVGWr0bLMreNfWktdls

# WebSocket
spring.websocket.allowed-origins=*

# Thêm cấu hình driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server port
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thang.0398173863@gmail.com
spring.mail.password=hoiu wwog gxzk yirj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

payos.clientId=c74ab267-3bd4-4977-9509-22389b7db3ad
payos.apiKey=2286b519-d39e-4f75-9de4-bbd18ac2e33c
payos.checksumKey=3aa09ad99a1d4071d4c4f31d1ac72b3444e342cdaa3594352869ccaade6b7fa3

